server:
  port: 8593
  
spring:
  datasource:
    dynamic:
      primary: story #设置默认的数据源或者数据源组,默认值即为master
      strict: false  #设置严格模式,默认false不启动. 启动后在未匹配到指定数据源时候会抛出异常,不启动则使用默认数据源.
      datasource:
        story:
          url: jdbc:sqlserver://192.168.1.33:1433;databasename=B_IT_01
          driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
          username: maxeit
          password: M@xe0133
#          driver-class-name: com.mysql.cj.jdbc.Driver
#          url: jdbc:mysql://192.168.1.189:3306/TryMyBatisConn_1?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Taipei
#          username: maxe0701
#          password: Love1025
        test:
          url: jdbc:sqlserver://192.168.1.33:1433;databasename=A_MAXE
          driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
          username: maxeit
          password: M@xe0133
#          driver-class-name: com.mysql.cj.jdbc.Driver
#          url: jdbc:mysql://192.168.1.189:3306/TryMyBatisConn_2?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Taipei
#          username: maxe0701
#          password: Love1025

logging:
  level:
    root: info
    org:
      springframework:
        jdbc:
          core: debug